### ISSUE TITLE
Gentle request for a 1.20.2 version - no pressure!

### ISSUE THREAD

**Issue by LessThanBenji** [Totobird-Creations/Configurable-Nether-Portals-Mod#2]
Hi, I hate it when people nag for updates, but this mod is just so perfect I have to know - are you planning to push out an updated .jar for 1.20.2? No stress if you aren't.

**Comment by Totobird-Creations** [comment]
Should be done. It's out on Modrinth at [https://modrinth.com/mod/configurable-nether-portals/version/1.1.1](https://modrinth.com/mod/configurable-nether-portals/version/1.1.1). Let me know if you have any issues.
